### ISSUE TITLE
missing data caused by inaturalist harvest http error code 500 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/inaturalist#2]
At time of writing (Sept 2017), only about 300 (expected about 20k) inaturalist observations are available through GloBI. On inspection of server log, a http status code 500 was found when attempting to harvest iNaturalist, causing a premature cancellation of the harvest process.

Perhaps consider introducing a GloBI-side cache of sorts, to be a little more resilient against iNaturalist outages.

@kueda FYI

from server log - 
```
cache/datasets/globalbioticinteractions/inaturalist/archive.zip] complete.
12:04:50,505 ERROR StudyImporterForGitHubData:63 - failed to import data from repo [globalbioticinteractions/inaturalist]
org.eol.globi.data.StudyImporterException: failed to import iNaturalist at [https://www.inaturalist.org/observation_field_values.json?type=taxon&page=4&per_page=100&quality_grade=research]
        at org.eol.globi.data.StudyImporterForINaturalist.retrieveDataParseResults(StudyImporterForINaturalist.java:164)
        at org.eol.globi.data.StudyImporterForINaturalist.importStudy(StudyImporterForINaturalist.java:112)
        at org.eol.globi.data.StudyImporterForGitHubData.importData(StudyImporterForGitHubData.java:86)
        at org.eol.globi.data.StudyImporterForGitHubData.importData(StudyImporterForGitHubData.java:59)
        at org.eol.globi.data.StudyImporterForGitHubData.importStudy(StudyImporterForGitHubData.java:43)
        at org.eol.globi.tool.Normalizer.importData(Normalizer.java:252)
        at org.eol.globi.tool.Normalizer.importData(Normalizer.java:238)
        at org.eol.globi.tool.Normalizer.importDatasets(Normalizer.java:126)
        at org.eol.globi.tool.Normalizer.run(Normalizer.java:96)
        at org.eol.globi.tool.Normalizer.main(Normalizer.java:67)
Caused by: org.eol.globi.data.StudyImporterException: failed to execute query to [https://www.inaturalist.org/observation_field_values.json?type=taxon&page=4&per_page=100&quality_grade=research]: status code [500]
        at org.eol.globi.data.StudyImporterForINaturalist.retrieveDataParseResults(StudyImporterForINaturalist.java:156)
        ... 9 more
```

**Comment by kueda** [comment]
That URL is working for me right now, so maybe we were deploying or down for some other reason. I don't think either case would trigger a 500 though, so if you see this happening consistently please holler again.

**Comment by jhpoelen** [comment]
Thanks for checking. I am hoping to get a more mature version GloBI shortly that uses cached versions of web resources like iNaturalist API responses. This way, the resource access and data crunching is a little more decouple and more resilient against temporary network outages or maintenance.
